/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "hbase_constants.h"

namespace apache { namespace hadoop { namespace hbase { namespace thrift {

const hbaseConstants g_hbase_constants;

hbaseConstants::hbaseConstants() {
}

}}}} // namespace

